apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../yamls

images:
- name: cloud-api-adaptor
  newName: quay.io/confidential-containers/cloud-api-adaptor
  newTag: dev-05d8f49c1d24f5c0a130db1e551a90fefabb0dee

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- literals:
  - CLOUD_PROVIDER="libvirt"
  - ENABLE_CLOUD_PROVIDER_EXTERNAL_PLUGIN="false"
  - CLOUD_CONFIG_VERIFY="false"
  - LIBVIRT_URI="qemu+ssh://wmoschet@192.168.122.1/system?no_verify=1"
  - LIBVIRT_NET="default"
  - LIBVIRT_POOL="default"
  - DISABLECVM="true"
  - SECURE_COMMS="false"
  - AA_KBC_PARAMS="cc_kbc::http://192.168.122.73:31015"
  - LIBVIRT_VOL_NAME="podvm-base.qcow2"
  name: peer-pods-cm
  namespace: confidential-containers-system
  #- LIBVIRT_LAUNCH_SECURITY="" #sev or s390-pv
  #- LIBVIRT_FIRMWARE="" # Uncomment and set if you want to change the firmware path. Defaults to /usr/share/edk2/ovmf/OVMF_CODE.fd
  #- LIBVIRT_VOL_NAME="" # Uncomment and set if you want to use a specific volume name. Defaults to podvm-base.qcow2
  #- PAUSE_IMAGE="" # Uncomment and set if you want to use a specific pause image
  #- VXLAN_PORT="" # Uncomment and set if you want to use a specific vxlan port. Defaults to 4789
##TLS_SETTINGS
  #- CACERT_FILE="/etc/certificates/ca.crt" # for TLS
  #- CERT_FILE="/etc/certificates/client.crt" # for TLS
  #- CERT_KEY="/etc/certificates/client.key" # for TLS
  #- TLS_SKIP_VERIFY="" # for testing only
##TLS_SETTINGS

   #- id_rsa # set - path to private key
secretGenerator:
- files:
  - auth.json
  name: auth-json-secret
  namespace: confidential-containers-system
- files:
  - id_rsa
  name: ssh-key-secret
  namespace: confidential-containers-system
- name: peer-pods-secret
  namespace: confidential-containers-system
