apiVersion: v1
kind: Pod
metadata:
  name: test-unsigned
spec:
  runtimeClassName: kata-remote
  containers:
    - name: test-container
      image: quay.io/prometheus/busybox:latest
      imagePullPolicy: Always
      command:
        - sleep
        - "infinity"
