# syntax=docker/dockerfile:1.5-labs

# registry.fedoraproject.org/fedora:41
ARG BASE_IMAGE=registry.fedoraproject.org/fedora@sha256:893f7eeffce8e3e2bb2bc62786ba5603fb1e0bd6ba07091acb892266b95bafdf
FROM --platform=$TARGETPLATFORM ${BASE_IMAGE} AS base

# DO NOT UPDATE THIS BY HAND !!
# Use hack/update-go-container.sh to update the version and hashes.
ARG GO_VERSION=1.25.9
ARG GO_LINUX_ARM64_SHA256=ec342e7389b7f489564ed5463c63b16cf8040023dabc7861256677165a8c0e2b
ARG GO_LINUX_AMD64_SHA256=00859d7bd6defe8bf84d9db9e57b9a4467b2887c18cd93ae7460e713db774bc1
ARG GO_LINUX_PPC64LE_SHA256=b0c41c7da1fc8d39020d65296a0dc54167afd9f76d67064e22c31ce3d839a739
ARG GO_LINUX_S390X_SHA256=0cf55136ac7eaccfc36d849054f849510ea289c2d959ffbed7b3866b4f484d17

FROM base AS base-amd64
ADD --checksum=sha256:${GO_LINUX_AMD64_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz .

FROM base AS base-arm64
ADD --checksum=sha256:${GO_LINUX_ARM64_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-arm64.tar.gz .

FROM base AS base-ppc64le
ADD --checksum=sha256:${GO_LINUX_PPC64LE_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-ppc64le.tar.gz .

FROM base AS base-s390x
ADD --checksum=sha256:${GO_LINUX_S390X_SHA256} https://go.dev/dl/go${GO_VERSION}.linux-s390x.tar.gz .

ARG TARGETARCH
FROM base-${TARGETARCH}

ARG TARGETARCH
ARG GO_VERSION
RUN tar -C /usr/local -xzf go${GO_VERSION}.linux-${TARGETARCH}.tar.gz && \
	rm go${GO_VERSION}.linux-${TARGETARCH}.tar.gz

# install cgo-related dependencies
RUN set -eux; \
	dnf install -y \
	g++ \
	gcc \
	glibc-devel \
	make \
	pkg-config \
	; \
	dnf clean all

ENV PATH=/usr/local/go/bin:$PATH

RUN set -eux; go version

ENV GOPATH=/go
ENV PATH=$GOPATH/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 1777 "$GOPATH"
WORKDIR $GOPATH
