# Check it can build the project for each cloud provider.
---
name: build
on: [pull_request]
env:
  GO_VERSION: '1.16'
jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          - aws
          - ibmcloud
          - libvirt
    steps:
      - name: Checkout the Kata Containers fork
        uses: actions/checkout@v3
        with:
          repository: yoheiueda/kata-containers
          ref: CCv0-peerpod
          path: kata-containers
      - name: Checkout the pull request code
        uses: actions/checkout@v3
        with:
          path: main
      - name: Setup Golang version ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make CLOUD_PROVIDER=${{ matrix.provider }} build
