# Run static checks.
---
name: check
on: [pull_request]
env:
  GO_VERSION: '1.18'
jobs:
  fmt:
    name: go fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make fmt
