# (C) Copyright Confidential Containers Contributors 2022.
# SPDX-License-Identifier: Apache-2.0
#
---
name: e2e tests

on:
  pull_request:
    types:
      # Adding 'labeled' to the list of activity types that trigger this event
      # (default: opened, synchronize, reopened) so that we can run this
      # workflow when the 'ok-to-test' label is added.
      # Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
      - opened
      - synchronize
      - reopened
      - labeled
jobs:
  podvm:
    name: podvm
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os:
          - centos
          - ubuntu
        provider:
          - generic
          #- vsphere
        arch:
          - amd64
          #- s390x
        #exclude:
          #- os: centos
          #  arch: s390x
          #- provider: vsphere
          #  arch: s390x
          #- provider: vsphere
          #  os: centos
    env:
      registry: quay.io/confidential-containers
      podvm_image: podvm-${{ matrix.provider }}-${{ matrix.os }}-${{ matrix.arch }}
      qcow2: podvm-${{ matrix.provider }}-${{ matrix.os }}-${{ matrix.arch }}.qcow2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract the podvm qcow2
        run: ./hack/download-image.sh ${{ env.registry }}/${{ env.podvm_image }} . -o ${{ env.qcow2 }}
        working-directory: podvm

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.qcow2 }}
          path: podvm/${{ env.qcow2 }}
          retention-days: 1

  image:
    name: image
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt') }}
    uses: ./.github/workflows/caa_build_and_push.yaml
    with:
      registry: ghcr.io/${{ github.repository_owner }}
      dev_tags: ci-pr${{ github.event.number  }}-dev
      release_tags: ci-pr${{ github.event.number  }}
    secrets: inherit

  # Run libvirt e2e tests if pull request labeled 'test_e2e_libvirt'
  e2e_libvirt:
    name: libvirt
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test_e2e_libvirt') }}
    needs: [podvm]
    uses: ./.github/workflows/e2e_libvirt_on_pull.yaml
    with:
      qcow2_artifact: podvm-generic-ubuntu-amd64.qcow2
    secrets: inherit