name: e2e libvirt on pull

on:
  workflow_call:
    inputs:
      podvm_qcow2:
        required: true
        type: string

jobs:
  podvm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore qcow2 cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: podvm/*
          fail-on-cache-miss: true
          key: foobar

      - name: run tests
        run: |
          echo "do nothing"