name: e2e libvirt

on:
  workflow_call:
    inputs:
      #podvm_qcow2:
      #  required: true
      #  type: string
      qcow2_artifact:
        required: true
        type: string
      install_directory_artifact:
        description: Use the install directory
        default: ''
        required: false
        type: string

jobs:
  podvm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.qcow2_artifact }}
          path: podvm

      - name: Mount the install directory
        if: ${{ inputs.install_directory_artifact != '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.install_directory_artifact }}
          path: install

      - name: run tests
        run: |
          ls podvm
          tree install
          git diff