name: e2e libvirt

on:
  workflow_call:
    inputs:
      #podvm_qcow2:
      #  required: true
      #  type: string
      qcow2_artifact:
        required: true
        type: string

jobs:
  podvm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.qcow2_artifact }}
          path: podvm
      - name: run tests
        run: |
          ls podvm