name: podvm_on_pull
on:
  workflow_dispatch:

jobs:
  podvm_builder:
    uses: ./.github/workflows/podvm_builder.yaml
    with:
      #caa_src_ref: ${{ github.sha }}
      caa_src_ref: ${{ github.ref }}
      registry: ghcr.io/${{ github.repository_owner }}
    secrets: inherit
  podvm_binaries:
    needs: [podvm_builder]
    uses: ./.github/workflows/podvm_binaries.yaml
    with:
      #caa_src_ref: ${{ github.sha }}
      caa_src_ref: ${{ github.ref }}
      registry: ghcr.io/${{ github.repository_owner }}
      builder_img_tag: ci-pr${{ github.event.number }}
    secrets: inherit
  podvm:
    needs: [podvm_binaries]
    uses: ./.github/workflows/podvm.yaml
    with:
      #caa_src_ref: ${{ github.sha }}
      caa_src_ref: ${{ github.ref }}
      registry: ghcr.io/${{ github.repository_owner }}
      binaries_img_tag: ci-pr${{ github.event.number }}
    secrets: inherit