name: Create Pod VM Image
on:
  workflow_run:
    workflows: ["Create Pod VM Binaries Image"]
    types:
      - completed

jobs:
  build:
    name: Create pod vm image
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [centos, ubuntu]
        arch: [amd64, s390x]
        provider: [generic, vsphere]
        include:
          - os: centos
            dockerfile: Dockerfile.podvm.centos
          - os: ubuntu
            dockerfile: Dockerfile.podvm
        exclude:
          - os: centos
            arch: s390x
          - provider: vsphere
            arch: s390x
          - provider: vsphere
            os: centos
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Quay container Registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    # Note: The `github.ref_name` contain the tag name on the `release` event. If
    # we ever change this workflow to run on other events (e.g. `push`) the value
    # of `github.ref_name` will be the branch or tag that triggered the event
    # and so it will be meaningless to tag the image with such as value.
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: |
          quay.io/confidential-containers/podvm-${{ matrix.provider }}-${{ matrix.os }}-${{ matrix.arch }}:latest
          quay.io/confidential-containers/podvm-${{ matrix.provider }}-${{ matrix.os }}-${{ matrix.arch }}:${{ github.sha }}
          quay.io/confidential-containers/podvm-${{ matrix.provider }}-${{ matrix.os }}-${{ matrix.arch }}:${{ github.ref_name }}
        push: true
        context: podvm
        platforms: linux/amd64
        file: |
          podvm/${{ matrix.dockerfile }}
        build-args: |
          "CLOUD_PROVIDER=${{ matrix.provider }}"
          "ARCH=${{ matrix.arch }}"
          "UBUNTU_IMAGE_URL="
          "UBUNTU_IMAGE_CHECKSUM="
          "BINARIES_IMG=quay.io/confidential-containers/podvm-binaries-${{ matrix.os }}-${{ matrix.arch }}"
