name: Create Pod VM Binaries Image
on:
  workflow_call:
    inputs:
      builder_img_tag:
        default: 'latest'
        required: false
        type: string
      registry:
        default: 'quay.io/confidential-containers'
        required: false
        type: string

jobs:
  build:
    name: Create pod vm binaries image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [centos, ubuntu]
        arch: [amd64, s390x]
        include:
          - os: centos
            dockerfile: Dockerfile.podvm_binaries.centos
          - os: ubuntu
            dockerfile: Dockerfile.podvm_binaries
        exclude:
          - os: centos
            arch: s390x
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker container Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Quay container Registry
      if: ${{ startsWith(inputs.registry, 'quay.io') }}
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Login to Github Container Registry
      if: ${{ startsWith(inputs.registry, 'ghcr.io') }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine image tags
      run: |
        event_name=${{ github.event_name }}
        img="${{ inputs.registry }}/podvm-binaries-${{ matrix.os }}-${{ matrix.arch }}"
        tags=""

        case "$event_name" in
        release)
          tags="${img}:latest,${img}:${{ github.sha }}" ;;
        pull_request|pull_request_target)
          tags="${img}:ci-pr${{ github.event.number }}" ;;
        esac

        echo "IMG_TAGS=$tags" >> "$GITHUB_ENV"

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: ${{ env.IMG_TAGS }}
        push: true
        context: podvm
        platforms: linux/amd64
        file: |
          podvm/${{ matrix.dockerfile }}
        build-args: |
          "ARCH=${{ matrix.arch }}"
          "BUILDER_IMG=${{ inputs.registry }}/podvm-builder-${{ matrix.os }}:${{ inputs.builder_img_tag }}"
          "UBUNTU_IMAGE_URL="
          "UBUNTU_IMAGE_CHECKSUM="
