name: Create Pod VM Builder Image
on:
  workflow_call:

jobs:
  build:
    name: Create pod vm builder image
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # Please keep this list in alphabetical order.
          - centos
          - ubuntu
        include:
          - os: centos
            dockerfile: Dockerfile.podvm_builder.centos
          - os: ubuntu
            dockerfile: Dockerfile.podvm_builder
        runner:
          - ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Parse versions.yaml
      run: |
        echo "GO_VERSION=$(yq r versions.yaml 'tools.golang')" >> $GITHUB_ENV
        echo "PROTOC_VERSION=$(yq r versions.yaml 'tools.protoc')" >> $GITHUB_ENV
        echo "RUST_VERSION=$(yq r versions.yaml 'tools.rust')" >> $GITHUB_ENV
        echo "CAA_SRC=$(yq r versions.yaml 'git.cloud-api-adaptor.url')" >> $GITHUB_ENV
        echo "CAA_SRC_REF=$(yq r versions.yaml 'git.cloud-api-adaptor.reference')" >> $GITHUB_ENV
        echo "KATA_SRC=$(yq r versions.yaml 'git.kata-containers.url')" >> $GITHUB_ENV
        echo "KATA_SRC_BRANCH=$(yq r versions.yaml 'git.kata-containers.reference')" >> $GITHUB_ENV

    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker container Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Quay container Registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: |
          quay.io/confidential-containers/podvm-builder-${{ matrix.os }}:latest
          quay.io/confidential-containers/podvm-builder-${{ matrix.os }}:${{ github.sha }}
        push: true
        context: podvm
        platforms: linux/amd64
        file: |
          podvm/${{ matrix.dockerfile }}
        build-args: |
          "GO_VERSION=${{ env.GO_VERSION }}"
          "PROTOC_VERSION=${{ env.PROTOC_VERSION }}"
          "RUST_VERSION=${{ env.RUST_VERSION }}"
          "CAA_SRC=${{ env.CAA_SRC }}"
          "CAA_SRC_REF=${{ env.CAA_SRC_REF }}"
          "KATA_SRC=${{ env.KATA_SRC }}"
          "KATA_SRC_BRANCH=${{ env.KATA_SRC_BRANCH }}"
