---
name: run aws

on:
  workflow_dispatch:

jobs:
  e2e:
    uses: ./.github/workflows/e2e_aws.yaml
    with:
      caa_image: "quay.io/confidential-containers/cloud-api-adaptor:v0.10.0-amd64"
      podvm_image: "quay.io/confidential-containers/podvm-generic-ubuntu-amd64:v0.10.0"
      git_ref: refs/heads/main
    secrets: inherit
